# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'
pod 'TwitterKit'
pod 'JSQMessagesViewController'

target 'hs-mobile-chat-app' do

end

target 'hs-mobile-chat-appTests' do

end

target 'hs-mobile-chat-appUITests' do

end

